export type HealingHallId =
  | "philosophy"
  | "elements"
  | "meditation"
  | "stories"
  | "creation"
  | "subscriptions"
  | "playground";

export type HealingModule = {
  id: string;
  hall: HealingHallId;
  title: string;
  originalName: string;
  summary: string;
  climate: string;
  entry: string;
  runtime: string;
  aiHook: string;
  pricing: string;
  roomLine: string;
  weatherLine: string;
  traceLine: string;
  quietEntrance: string;
  coverTone: "mist" | "wood" | "water" | "stone" | "paper" | "desert" | "garden";
};

export type HealingHall = {
  id: HealingHallId;
  title: string;
  shortTitle: string;
  href: string;
  hero: string;
  summary: string;
  climate: string;
};

export const healingHalls: readonly HealingHall[] = [
  {
    id: "philosophy",
    title: "Paper Light Room",
    shortTitle: "Paper Light",
    href: "/healing/philosophy",
    hero: "Daily light interactions for short lines, symbols, wishes, and kindness.",
    summary: "A high-frequency hall for small browser pauses that do not become tasks.",
    climate: "mist, paper, quiet linework",
  },
  {
    id: "elements",
    title: "Inner Weather Room",
    shortTitle: "Inner Weather",
    href: "/healing/elements",
    hero: "Color, plant, room, and seasonal fit without heavy mystic framing.",
    summary: "A practical hall for mood, materials, color, and home atmosphere.",
    climate: "plant light, mineral color, soft rooms",
  },
  {
    id: "meditation",
    title: "Slower Room",
    shortTitle: "Slower Room",
    href: "/healing/meditation",
    hero: "Slow visual and audio surfaces for leaving the tab open.",
    summary: "No score, no streak, no pressure to complete the session.",
    climate: "cloud, water, smoke, slow shadow",
  },
  {
    id: "stories",
    title: "Letter Shelf",
    shortTitle: "Letter Shelf",
    href: "/healing/stories",
    hero: "Anonymous letters, time capsules, object stories, and quiet resonance.",
    summary: "A soft emotional layer without continuous stream behavior or social pressure.",
    climate: "paper, envelope, distance, warm archive",
  },
  {
    id: "creation",
    title: "Nearby Light",
    shortTitle: "Nearby Light",
    href: "/healing/creation",
    hero: "Light AI-assisted creation for portraits, trees, maps, and elemental images.",
    summary: "Small creative surfaces that can produce a keepsake without becoming a tool suite.",
    climate: "ink, line, tree, star map",
  },
  {
    id: "subscriptions",
    title: "Monthly Shelf",
    shortTitle: "Monthly Shelf",
    href: "/healing/subscriptions",
    hero: "Monthly quiet objects, scents, sounds, tea, texture, and regional variants.",
    summary: "Physical continuity with digital companions, kept simple and clear.",
    climate: "parcel, wood, candle, tea, mineral",
  },
  {
    id: "playground",
    title: "Quiet Courtyard",
    shortTitle: "Courtyard",
    href: "/healing/playground",
    hero: "Low-pressure interactions with no failure, no timer pressure, and no measurement loop.",
    summary: "Small browser play surfaces for gardens, letters, texture, water, and stars.",
    climate: "garden, stars, sand, water, notes",
  },
] as const;

type BrowserAirModuleName = {
  title: string;
  roomLine: string;
  weatherLine: string;
  traceLine: string;
  quietEntrance: string;
};

const browserAirModuleNames: Record<string, BrowserAirModuleName> = {
  "daily-verse": {
    title: "Morning Line",
    roomLine: "A short line left in the browser before the day becomes loud.",
    weatherLine: "mist, paper light, one sentence",
    traceLine: "The page remembers one quiet line and lets it pass.",
    quietEntrance: "Read slowly",
  },
  "wisdom-scroll-generator": {
    title: "Paper Window",
    roomLine: "A vertical page for one plain thought and a little room light.",
    weatherLine: "paper edge, ink air, soft margin",
    traceLine: "A line can stay as paper without becoming a post.",
    quietEntrance: "Open paper",
  },
  "rune-inner-self": {
    title: "Small Mark",
    roomLine: "A thin personal mark, kept light enough to sit near the desk.",
    weatherLine: "linework, stone, quiet meaning",
    traceLine: "The mark stays small and does not explain the person.",
    quietEntrance: "Find a mark",
  },
  "life-flower-sigil": {
    title: "Season Mark",
    roomLine: "A pale seasonal shape for a name, a date, and a little air.",
    weatherLine: "seasonal geometry, pale light",
    traceLine: "The shape rests like a note in a drawer.",
    quietEntrance: "Let it form",
  },
  "kindness-blank-canvas": {
    title: "Blank Kindness",
    roomLine: "An empty paper corner where one small response is enough.",
    weatherLine: "blank paper, one quiet mark",
    traceLine: "Nothing here asks for more than one human trace.",
    quietEntrance: "Leave one mark",
  },
  "wish-lantern": {
    title: "Lantern Air",
    roomLine: "A warm paper light for a short wish that does not need a crowd.",
    weatherLine: "night air, warm paper, slow lift",
    traceLine: "The wish rises and the browser keeps the room gentle.",
    quietEntrance: "Lift a light",
  },
  "five-elements-harmony": {
    title: "Inner Weather",
    roomLine: "A practical weather corner for color, rest, scent, and living rhythm.",
    weatherLine: "mineral color, linen, ordinary balance",
    traceLine: "The result should feel like a room note, not a report.",
    quietEntrance: "Check the weather",
  },
  "five-color-vibe": {
    title: "Color Weather",
    roomLine: "A soft color corner for the clothes, rooms, and days nearby.",
    weatherLine: "muted cards, pale color, easy use",
    traceLine: "Color appears as atmosphere before advice.",
    quietEntrance: "See the colors",
  },
  "vibe-color-palette": {
    title: "Linen Palette",
    roomLine: "A longer color shelf for rooms, desks, and small wearable choices.",
    weatherLine: "linen warmth, mineral gray, muted accent",
    traceLine: "The palette stays quiet enough to live with.",
    quietEntrance: "Open palette",
  },
  "space-harmony-quiz": {
    title: "Shelf Balance",
    roomLine: "A room corner for light, placement, and small adjustments.",
    weatherLine: "quiet shelf, window air, softened room",
    traceLine: "The room is not fixed; it is allowed to settle.",
    quietEntrance: "Look around",
  },
  "seasonal-energy-check": {
    title: "Season Room",
    roomLine: "A slow seasonal check for rest, scent, color, and daily rhythm.",
    weatherLine: "seasonal light, ordinary rhythm",
    traceLine: "The season is treated as weather, not a task.",
    quietEntrance: "Enter season",
  },
  "soul-plant-match": {
    title: "Plant Nearby",
    roomLine: "A plant companion corner for shade, temperament, and quiet care.",
    weatherLine: "plant light, shade, care note",
    traceLine: "A plant can be nearby without becoming symbolic weight.",
    quietEntrance: "Meet a plant",
  },
  "cloud-meditation-altar": {
    title: "Cloud Room",
    roomLine: "A cloud surface that can stay open without asking to be completed.",
    weatherLine: "cloud, fog, water, wood sound",
    traceLine: "The tab may remain open like a quiet window.",
    quietEntrance: "Open cloud",
  },
  "virtual-incense-altar": {
    title: "Incense Table",
    roomLine: "A slow smoke table with forest air and no managed ritual pressure.",
    weatherLine: "smoke, forest, muted table",
    traceLine: "The smoke moves softly and the room does the rest.",
    quietEntrance: "Light softly",
  },
  "quiet-silence-timer": {
    title: "Quiet Minute",
    roomLine: "A small silence room with no loud numbers and no finish line.",
    weatherLine: "fog movement, low light",
    traceLine: "Time becomes softer when it is not counted loudly.",
    quietEntrance: "Begin quiet",
  },
  "slow-clock": {
    title: "Slow Clock",
    roomLine: "A desktop clock without second-hand pressure.",
    weatherLine: "slow cloud time",
    traceLine: "The hour can stay visible without becoming urgent.",
    quietEntrance: "Open clock",
  },
  "quiet-ferry": {
    title: "Quiet Ferry",
    roomLine: "A small boat moving through a minimal river at browser speed.",
    weatherLine: "river, boat, dawn, night",
    traceLine: "The ferry passes without asking where to arrive.",
    quietEntrance: "Enter ferry",
  },
  "mindful-path": {
    title: "Slow Path",
    roomLine: "A short walking passage with water, wind, and low movement.",
    weatherLine: "path, stream, low wind",
    traceLine: "Walking here is a room atmosphere, not progress.",
    quietEntrance: "Walk slowly",
  },
  "stone-alignment": {
    title: "Stone Table",
    roomLine: "A pale table where stones can be placed and left alone.",
    weatherLine: "stone, balance, pale table",
    traceLine: "The stones do not score the hand that moved them.",
    quietEntrance: "Place stones",
  },
  "time-capsule": {
    title: "Future Letter",
    roomLine: "A sealed paper corner for a letter that may wait a long time.",
    weatherLine: "sealed paper, long time",
    traceLine: "The letter belongs to time before it belongs to sending.",
    quietEntrance: "Write slowly",
  },
  "story-drift": {
    title: "Drifting Bottle",
    roomLine: "A distant water surface for short anonymous fragments.",
    weatherLine: "bottle, water, distance",
    traceLine: "A story can drift without becoming a conversation.",
    quietEntrance: "Let it drift",
  },
  "object-story-archive": {
    title: "Object Shelf",
    roomLine: "A shelf for old object photos and small human notes.",
    weatherLine: "object archive, human note",
    traceLine: "Objects are kept as traces before they become anything else.",
    quietEntrance: "Add a trace",
  },
  "mood-envelope": {
    title: "Closed Envelope",
    roomLine: "A paper envelope for a difficult feeling to become quieter.",
    weatherLine: "envelope, fog, release",
    traceLine: "The envelope closes without asking for a reply.",
    quietEntrance: "Seal softly",
  },
  "distant-resonance": {
    title: "Distant Mountain",
    roomLine: "A same-moment line from far away, without direct conversation.",
    weatherLine: "distant mountain, one sentence",
    traceLine: "Another room may echo without pulling closer.",
    quietEntrance: "Send a state",
  },
  "kindness-seed": {
    title: "Passing Seed",
    roomLine: "A small note that can move from one person to another room.",
    weatherLine: "seed, handoff, green quiet",
    traceLine: "Kindness travels better when it stays ordinary.",
    quietEntrance: "Pass a seed",
  },
  "life-vibe-portrait": {
    title: "Line Portrait",
    roomLine: "A minimal line portrait kept as a small personal keepsake.",
    weatherLine: "line portrait, open space",
    traceLine: "The portrait stays light and does not define the person.",
    quietEntrance: "Open line",
  },
  "life-vibe-tree": {
    title: "Quiet Tree",
    roomLine: "A mood tree with branches, mist, and yearly light.",
    weatherLine: "tree, air, yearly change",
    traceLine: "The tree grows slowly enough to be remembered.",
    quietEntrance: "Grow softly",
  },
  "birth-vibe-map": {
    title: "Star Map",
    roomLine: "A quiet map of time and place without prediction pressure.",
    weatherLine: "star field, ink map",
    traceLine: "The sky stays as a keepsake, not an answer.",
    quietEntrance: "Open map",
  },
  "element-craft-studio": {
    title: "Element Table",
    roomLine: "A small table for water, wind, mountain, cloud, and intention.",
    weatherLine: "element tiles, slow composition",
    traceLine: "Composition stays like arranging objects on a table.",
    quietEntrance: "Compose slowly",
  },
  "quiet-moments-subscription": {
    title: "Monthly Quiet",
    roomLine: "A monthly shelf for incense, sound, and a small table object.",
    weatherLine: "parcel, scent, sound, quiet table",
    traceLine: "The parcel arrives like part of the room, not a campaign.",
    quietEntrance: "View shelf",
  },
  "seasonal-quiet-decor-subscription": {
    title: "Seasonal Shelf",
    roomLine: "A seasonal desk object with room placement and low sound.",
    weatherLine: "seasonal desk, small parcel",
    traceLine: "The object follows weather instead of urgency.",
    quietEntrance: "View season",
  },
  "calm-candle-crystal-subscription": {
    title: "Warm Mineral",
    roomLine: "A candle and mineral shelf with a small mood card.",
    weatherLine: "warm light, mineral surface",
    traceLine: "Light and stone stay ordinary enough to use.",
    quietEntrance: "View light",
  },
  "quiet-soundscape-subscription": {
    title: "Small Sound",
    roomLine: "A small sound object with a nature-air companion.",
    weatherLine: "small instrument, slow sound",
    traceLine: "Sound stays in the background of the room.",
    quietEntrance: "View sound",
  },
  "tactile-calm-subscription": {
    title: "Texture Shelf",
    roomLine: "A monthly natural texture object with a short material note.",
    weatherLine: "wood grain, stone, hand feeling",
    traceLine: "Texture gives the hand a quiet place to return.",
    quietEntrance: "View texture",
  },
  "quiet-tea-moments": {
    title: "Tea Hour",
    roomLine: "A caffeine-free tea corner with ceramic warmth and slow drinking.",
    weatherLine: "tea, ceramic, warm paper",
    traceLine: "The cup keeps the hour soft.",
    quietEntrance: "View tea",
  },
  "desert-calm-subscription": {
    title: "Desert Evening",
    roomLine: "A warm desert shelf for scent, stone, and evening air.",
    weatherLine: "desert stone, warm dusk",
    traceLine: "The desert stays low and room-like.",
    quietEntrance: "View dusk",
  },
  "arabesque-quiet-craft-subscription": {
    title: "Tile Fragment",
    roomLine: "A handmade tile or ceramic fragment with pattern and quiet craft.",
    weatherLine: "tile, pattern, quiet craft",
    traceLine: "Pattern remains a human trace, not ornament pressure.",
    quietEntrance: "View tile",
  },
  "date-sage-quiet-tea": {
    title: "Courtyard Tea",
    roomLine: "A regional herbal tea corner with copper and courtyard air.",
    weatherLine: "tea, copper, courtyard quiet",
    traceLine: "The courtyard stays close to the cup.",
    quietEntrance: "View tea",
  },
  "emotion-garden": {
    title: "Soft Garden",
    roomLine: "A no-fail garden where small feelings can grow slowly.",
    weatherLine: "soft garden, daily change",
    traceLine: "Nothing here needs to be completed.",
    quietEntrance: "Open garden",
  },
  "quiet-letters": {
    title: "Quiet Letters",
    roomLine: "Warm anonymous letters with no pressure to perform or answer quickly.",
    weatherLine: "letter paper, warm margin",
    traceLine: "A letter can be received without creating a loop.",
    quietEntrance: "Open letters",
  },
  "desert-starscape": {
    title: "Desert Stars",
    roomLine: "A slow desert horizon with stars, dusk, moon, and quiet air.",
    weatherLine: "sand, stars, dusk light",
    traceLine: "The sky moves slowly enough to leave open.",
    quietEntrance: "Open stars",
  },
  "arabesque-garden": {
    title: "Courtyard Garden",
    roomLine: "A no-fail courtyard with desert roses, jasmine, and still objects.",
    weatherLine: "courtyard, mosaic, desert plants",
    traceLine: "The garden stays a room, not a challenge.",
    quietEntrance: "Open courtyard",
  },
  "sand-texture-zen": {
    title: "Sand Texture",
    roomLine: "A slow sand surface with geometry and no time limit.",
    weatherLine: "sand texture, soft geometry",
    traceLine: "The pattern can remain unfinished.",
    quietEntrance: "Open sand",
  },
  "courtyard-water-calm": {
    title: "Courtyard Water",
    roomLine: "A water surface with slow drops, ripples, and adjustable pace.",
    weatherLine: "water, tile, slow ripple",
    traceLine: "The water keeps moving without asking anything back.",
    quietEntrance: "Open water",
  },
  "quiet-arabic-notes": {
    title: "Warm Wall Notes",
    roomLine: "Warm regional notes on a quiet wall, readable without pressure.",
    weatherLine: "wall note, warm paper, regional texture",
    traceLine: "The wall keeps small notes like room memory.",
    quietEntrance: "Open notes",
  },
};

const healingModuleSeeds = [
  {
    id: "daily-verse",
    hall: "philosophy",
    title: "The Daily Verse",
    originalName: "每日一签・东方启示",
    summary: "A daily short line with mist, cloud, or ink movement and a gentle wallpaper output.",
    climate: "morning mist and one sentence",
    entry: "Receive the line",
    runtime: "Daily line rotation, soft reveal, wallpaper placeholder",
    aiHook: "Line translation, wallpaper crop, tone adaptation",
    pricing: "Free low-res image / $1.99 high-res export",
    coverTone: "mist",
  },
  {
    id: "wisdom-scroll-generator",
    hall: "philosophy",
    title: "Paper Window",
    originalName: "哲理卷轴生成器",
    summary: "A vertical quiet scroll for a short thought, cover image, or social card.",
    climate: "paper, ink edge, vertical breathing",
    entry: "Make a scroll",
    runtime: "Template selection and export shell",
    aiHook: "Short line refinement and layout fit",
    pricing: "Free base template / $3.99 custom color and batch download",
    coverTone: "paper",
  },
  {
    id: "rune-inner-self",
    hall: "philosophy",
    title: "Rune of Inner Self",
    originalName: "内在人格符文",
    summary: "A minimal guardian mark from personality cues, with no heavy symbol system.",
    climate: "thin linework and quiet meaning",
    entry: "Find a mark",
    runtime: "Prompt shell, mark preview, meaning placeholder",
    aiHook: "Symbol generation and concise interpretation",
    pricing: "Free small image / $4.99 HD and meaning card",
    coverTone: "stone",
  },
  {
    id: "life-flower-sigil",
    hall: "philosophy",
    title: "Life Flower Sigil",
    originalName: "生命之花印记",
    summary: "A symmetrical line sigil from name and birth season for a calm keepsake.",
    climate: "seasonal geometry and pale air",
    entry: "Draw a sigil",
    runtime: "Name, season, preview shell",
    aiHook: "Geometry variant and short meaning",
    pricing: "Free small image / $4.99 HD and personal format",
    coverTone: "mist",
  },
  {
    id: "kindness-blank-canvas",
    hall: "philosophy",
    title: "Kindness Blank Canvas",
    originalName: "善意留白",
    summary: "A blank ink field where a visitor can leave one minimal response symbol.",
    climate: "blank paper and one quiet mark",
    entry: "Leave one mark",
    runtime: "Single-symbol response shell, local save placeholder",
    aiHook: "Symbol moderation and visual harmony",
    pricing: "Free one canvas daily / $2.99 gold template and saved set",
    coverTone: "paper",
  },
  {
    id: "wish-lantern",
    hall: "philosophy",
    title: "Wish Lantern",
    originalName: "善意许愿灯",
    summary: "A virtual lantern for a short anonymous wish, rising without chat pressure.",
    climate: "night air and warm paper light",
    entry: "Lift a lantern",
    runtime: "Wish input, floating field, anonymous view shell",
    aiHook: "Gentle language cleanup and safety check",
    pricing: "Free one lantern daily / $3.99 gold lantern and longer float",
    coverTone: "mist",
  },
  {
    id: "five-elements-harmony",
    hall: "elements",
    title: "Five Elements Harmony",
    originalName: "五行能量匹配器",
    summary: "A practical temperament report with color, rest, scent, and living suggestions.",
    climate: "mineral elements and calm report",
    entry: "Check harmony",
    runtime: "Birth or temperament input, report shell",
    aiHook: "Report explanation and lifestyle suggestions",
    pricing: "Free base report / $3.99 full living guide",
    coverTone: "stone",
  },
  {
    id: "five-color-vibe",
    hall: "elements",
    title: "Five-Color Vibe",
    originalName: "五行色彩诊断",
    summary: "A current color mood check for clothing, home, and social settings.",
    climate: "soft color cards and clear use",
    entry: "See colors",
    runtime: "Mood test and three-color output",
    aiHook: "Scene palette expansion",
    pricing: "Free three colors / $3.99 seasonal cards",
    coverTone: "paper",
  },
  {
    id: "vibe-color-palette",
    hall: "elements",
    title: "Vibe Color Palette",
    originalName: "气韵配色卡",
    summary: "A longer-term palette for personal rooms, desk surfaces, and wearable color.",
    climate: "linen, mineral gray, muted accents",
    entry: "Build palette",
    runtime: "Trait input and palette card shell",
    aiHook: "Palette naming and room examples",
    pricing: "Free three palettes / $3.99 full seasonal guide",
    coverTone: "paper",
  },
  {
    id: "space-harmony-quiz",
    hall: "elements",
    title: "Space Harmony Quiz",
    originalName: "居所能量小测",
    summary: "A room atmosphere quiz that gives simple placement and light suggestions.",
    climate: "quiet room and shelf balance",
    entry: "Check the room",
    runtime: "Room quiz and suggestion shell",
    aiHook: "Room-specific placement notes",
    pricing: "Free base guide / $3.99 complete arrangement guide",
    coverTone: "wood",
  },
  {
    id: "seasonal-energy-check",
    hall: "elements",
    title: "Seasonal Energy Check",
    originalName: "四季气运自测",
    summary: "A quarterly state check with rest, scent, color, and routine suggestions.",
    climate: "seasonal light and ordinary rhythm",
    entry: "Check season",
    runtime: "Quarter state card and advice shell",
    aiHook: "Seasonal recommendation refinement",
    pricing: "Free short check / $3.99 full seasonal report",
    coverTone: "garden",
  },
  {
    id: "soul-plant-match",
    hall: "elements",
    title: "Soul Plant Match",
    originalName: "灵魂草木配对",
    summary: "A plant companion match from everyday state and temperament.",
    climate: "plant, shade, quiet care",
    entry: "Meet a plant",
    runtime: "Plant match and care note shell",
    aiHook: "Plant illustration and care language",
    pricing: "Free intro / $3.99 plant meaning and illustration",
    coverTone: "garden",
  },
  {
    id: "cloud-meditation-altar",
    hall: "meditation",
    title: "Cloud Meditation Altar",
    originalName: "云影静心台",
    summary: "A static cloud and sound surface for leaving open without being managed.",
    climate: "cloud, fog, water, wood sound",
    entry: "Open cloud",
    runtime: "Ambient surface, sound selector placeholder",
    aiHook: "Personal soundscape and background adaptation",
    pricing: "Free base sounds / $5.99 custom soundscape and background",
    coverTone: "mist",
  },
  {
    id: "virtual-incense-altar",
    hall: "meditation",
    title: "Virtual Incense Altar",
    originalName: "虚拟焚香台",
    summary: "A slow incense surface with smoke movement and forest sound.",
    climate: "smoke, forest, muted table",
    entry: "Light incense",
    runtime: "Smoke loop and sound placeholder",
    aiHook: "Custom pattern and long-session tone",
    pricing: "Free three scents / $4.99 long mode and custom pattern",
    coverTone: "wood",
  },
  {
    id: "quiet-silence-timer",
    hall: "meditation",
    title: "Quiet Silence Timer",
    originalName: "断念静默计时器",
    summary: "A no-pressure silence timer with no loud numbers and no completion pressure.",
    climate: "fog movement and low light",
    entry: "Begin quiet",
    runtime: "Soft timer shell, no loud display",
    aiHook: "Quiet tone and background selection",
    pricing: "Free base timer / $3.99 custom background and sound",
    coverTone: "mist",
  },
  {
    id: "slow-clock",
    hall: "meditation",
    title: "Slow Clock",
    originalName: "慢钟时刻",
    summary: "A slow desktop clock with no second-hand pressure.",
    climate: "slow cloud time",
    entry: "Open clock",
    runtime: "Full-screen clock shell",
    aiHook: "Time-of-day atmosphere adaptation",
    pricing: "Free base clock / $2.99 additional quiet layouts",
    coverTone: "water",
  },
  {
    id: "quiet-ferry",
    hall: "meditation",
    title: "Quiet Ferry",
    originalName: "孤舟渡",
    summary: "A small boat drifting on a minimal river with water sound and soft lights.",
    climate: "river, boat, dawn and night",
    entry: "Enter ferry",
    runtime: "Boat drift surface and light placement shell",
    aiHook: "Scene shift and water audio matching",
    pricing: "Free day mode / $4.99 night, dawn, and long-stay modes",
    coverTone: "water",
  },
  {
    id: "mindful-path",
    hall: "meditation",
    title: "Mindful Path",
    originalName: "静心行走路径",
    summary: "A short slow-walk scene with water, wind, and path movement.",
    climate: "path, stream, low wind",
    entry: "Walk slowly",
    runtime: "Short path progression shell",
    aiHook: "Route variation and ambient line",
    pricing: "Free base path / $3.99 forest, cloud, and valley paths",
    coverTone: "garden",
  },
  {
    id: "stone-alignment",
    hall: "meditation",
    title: "Stone Alignment",
    originalName: "灵石归位",
    summary: "A drag-and-place stone balance surface that ends with one short line.",
    climate: "stone, balance, pale table",
    entry: "Place stones",
    runtime: "Drag shell and balance result placeholder",
    aiHook: "Balance phrase and poster export",
    pricing: "Free base stones / $3.99 hidden layouts and poster",
    coverTone: "stone",
  },
  {
    id: "time-capsule",
    hall: "stories",
    title: "Time Capsule",
    originalName: "时光胶囊・写给未来",
    summary: "A future letter surface with optional object attachment later.",
    climate: "sealed paper and long time",
    entry: "Write future mail",
    runtime: "Letter draft and date shell",
    aiHook: "Gentle copy support and object relation",
    pricing: "Free one letter / $4.99 multiple letters and object link",
    coverTone: "paper",
  },
  {
    id: "story-drift",
    hall: "stories",
    title: "Story Drift",
    originalName: "故事漂流瓶",
    summary: "Anonymous short stories, secrets, or regrets that can be dropped and found.",
    climate: "bottle, water, distance",
    entry: "Drop a story",
    runtime: "Anonymous story shell, read-only retrieval",
    aiHook: "Safety review and language softening",
    pricing: "Free reading / small maintenance fee after repeated retrieval",
    coverTone: "water",
  },
  {
    id: "object-story-archive",
    hall: "stories",
    title: "Object & Story Archive",
    originalName: "一物一事・馆藏故事",
    summary: "Old object photo and story collection for memory without selling-floor energy.",
    climate: "object archive and human note",
    entry: "Add an object story",
    runtime: "Upload story shell and review placeholder",
    aiHook: "Story cleanup and object tagging",
    pricing: "Free upload / $5.00 featured archive period",
    coverTone: "wood",
  },
  {
    id: "mood-envelope",
    hall: "stories",
    title: "Mood Envelope",
    originalName: "情绪风信封",
    summary: "Write a difficult feeling into a virtual envelope and let it close.",
    climate: "envelope, fog, release",
    entry: "Seal a feeling",
    runtime: "Envelope input and dissolve shell",
    aiHook: "Private rewrite and soft release phrase",
    pricing: "Free experience / $2.99 symbol poster",
    coverTone: "paper",
  },
  {
    id: "distant-resonance",
    hall: "stories",
    title: "Distant Resonance",
    originalName: "远山共鸣",
    summary: "A same-moment text surface that shows resonance without direct chat.",
    climate: "distant mountain and one sentence",
    entry: "Send a state",
    runtime: "Anonymous state shell and read-only matching",
    aiHook: "Safety grouping and resonance tag",
    pricing: "Free once daily / $2.99 symbol and save option",
    coverTone: "mist",
  },
  {
    id: "kindness-seed",
    hall: "stories",
    title: "Kindness Seed",
    originalName: "善意种子传递",
    summary: "A virtual seed with a short note that can move from person to person.",
    climate: "seed, handoff, green quiet",
    entry: "Pass a seed",
    runtime: "Seed note and passage shell",
    aiHook: "Kindness note moderation",
    pricing: "Free daily pass / $2.99 gold seed and symbol",
    coverTone: "garden",
  },
  {
    id: "life-vibe-portrait",
    hall: "creation",
    title: "Life Vibe Portrait",
    originalName: "人生气韵画像",
    summary: "A minimal line portrait from temperament words for profile or keepsake use.",
    climate: "line portrait and open space",
    entry: "Make portrait",
    runtime: "Keyword input and preview shell",
    aiHook: "Portrait generation and style fit",
    pricing: "Free small image / $4.99 HD and personal use export",
    coverTone: "paper",
  },
  {
    id: "life-vibe-tree",
    hall: "creation",
    title: "Life Vibe Tree",
    originalName: "人生气韵树",
    summary: "A mood tree generated from current state, branches, mist, and light.",
    climate: "tree, air, yearly change",
    entry: "Grow a tree",
    runtime: "Mood input and tree preview shell",
    aiHook: "Tree image and yearly versioning",
    pricing: "Free small tree / $4.99 HD and yearly keepsake",
    coverTone: "garden",
  },
  {
    id: "birth-vibe-map",
    hall: "creation",
    title: "Birth Vibe Map",
    originalName: "专属生辰星图",
    summary: "A quiet star-map inspired by birth time and place, without horoscope framing.",
    climate: "star field and ink map",
    entry: "Make map",
    runtime: "Birth input and map shell",
    aiHook: "Map styling and private edition",
    pricing: "Free low-res / $4.99 HD private layout",
    coverTone: "mist",
  },
  {
    id: "element-craft-studio",
    hall: "creation",
    title: "Element Table",
    originalName: "万物合成工坊",
    summary: "Drag water, wind, mountain, cloud, and intention into a small image surface.",
    climate: "element tiles and slow composition",
    entry: "Compose elements",
    runtime: "Drag shell and image output placeholder",
    aiHook: "Image generation and export variants",
    pricing: "Free base library / $3.99 hidden elements and set download",
    coverTone: "water",
  },
  {
    id: "quiet-moments-subscription",
    hall: "subscriptions",
    title: "Monthly Quiet",
    originalName: "静心时刻・香氛/音钵订阅",
    summary: "Monthly incense holder, incense or small sound bowl with a short audio companion.",
    climate: "parcel, scent, sound, quiet table",
    entry: "View subscription",
    runtime: "Monthly shelf shell and order interest link",
    aiHook: "Monthly pairing and audio card",
    pricing: "$12.99 / month placeholder",
    coverTone: "wood",
  },
  {
    id: "seasonal-quiet-decor-subscription",
    hall: "subscriptions",
    title: "Seasonal Shelf",
    originalName: "季节风物・治愈桌面小物订阅",
    summary: "Monthly desk object with a room placement guide and white-noise companion.",
    climate: "seasonal desk and small parcel",
    entry: "View decor",
    runtime: "Monthly object shell",
    aiHook: "Room placement guide and audio matching",
    pricing: "$12.99 / month placeholder",
    coverTone: "wood",
  },
  {
    id: "calm-candle-crystal-subscription",
    hall: "subscriptions",
    title: "Warm Mineral",
    originalName: "情绪疗愈・香薰蜡烛&天然晶石订阅",
    summary: "A monthly candle and crystal with short mood cards and simple care notes.",
    climate: "warm light and mineral surface",
    entry: "View candle set",
    runtime: "Set preview and interest shell",
    aiHook: "Mood card generation",
    pricing: "$13.99 / month placeholder",
    coverTone: "stone",
  },
  {
    id: "quiet-soundscape-subscription",
    hall: "subscriptions",
    title: "Small Sound",
    originalName: "自然音景・冥想乐器订阅",
    summary: "A monthly small sound instrument with a nature audio companion.",
    climate: "small instrument and slow sound",
    entry: "View soundscape",
    runtime: "Instrument preview shell",
    aiHook: "Audio pairing and simple notation card",
    pricing: "$12.99 / month placeholder",
    coverTone: "water",
  },
  {
    id: "tactile-calm-subscription",
    hall: "subscriptions",
    title: "Texture Shelf",
    originalName: "触摸治愈・天然纹理手作订阅",
    summary: "A monthly natural texture object with a short material story.",
    climate: "wood grain, stone, hand feel",
    entry: "View texture",
    runtime: "Material story shell",
    aiHook: "Texture note and tactile guide",
    pricing: "$13.99 / month placeholder",
    coverTone: "stone",
  },
  {
    id: "quiet-tea-moments",
    hall: "subscriptions",
    title: "Quiet Tea Moments",
    originalName: "静谧茶语・无咖啡因茶包订阅",
    summary: "Caffeine-free herbal tea with a small spoon and slow-drink audio.",
    climate: "tea, ceramic, warm paper",
    entry: "View tea",
    runtime: "Tea set preview shell",
    aiHook: "Tea note and audio companion",
    pricing: "$12.99 / month placeholder",
    coverTone: "wood",
  },
  {
    id: "desert-calm-subscription",
    hall: "subscriptions",
    title: "Desert Evening",
    originalName: "沙漠静谧・沙丘香氛与沙漠晶石订阅",
    summary: "A regional desert scent and crystal subscription with evening wind audio.",
    climate: "desert stone and warm dusk",
    entry: "View desert calm",
    runtime: "Regional subscription shell",
    aiHook: "Region-sensitive scent and note pairing",
    pricing: "$13.99 / month placeholder",
    coverTone: "desert",
  },
  {
    id: "arabesque-quiet-craft-subscription",
    hall: "subscriptions",
    title: "Tile Fragment",
    originalName: "阿拉伯纹样・极简手作瓷砖/陶片订阅",
    summary: "A small handmade tile or ceramic fragment with pattern story and coloring line.",
    climate: "tile, pattern, quiet craft",
    entry: "View craft",
    runtime: "Regional craft shell",
    aiHook: "Pattern history and line-art guide",
    pricing: "$12.99 / month placeholder",
    coverTone: "desert",
  },
  {
    id: "date-sage-quiet-tea",
    hall: "subscriptions",
    title: "Date & Sage Quiet Tea",
    originalName: "椰枣与安息・无咖啡因草本茶订阅",
    summary: "Regional herbal tea with a small copper spoon and courtyard sound companion.",
    climate: "tea, copper, courtyard quiet",
    entry: "View tea",
    runtime: "Regional tea shell",
    aiHook: "Tea card and courtyard audio",
    pricing: "$12.99 / month placeholder",
    coverTone: "desert",
  },
  {
    id: "emotion-garden",
    hall: "playground",
    title: "Emotion Garden",
    originalName: "情绪花园・无压力种植",
    summary: "A no-fail garden where emotion seeds grow slowly without task pressure.",
    climate: "soft garden and daily change",
    entry: "Open garden",
    runtime: "Local garden shell and plant slots",
    aiHook: "Plant naming and garden tone",
    pricing: "Free base garden / $2.99 rare seeds and garden backgrounds",
    coverTone: "garden",
  },
  {
    id: "quiet-letters",
    hall: "playground",
    title: "Quiet Letters",
    originalName: "文字疗愈・匿名温暖信件",
    summary: "Anonymous warm letters with no pressure to perform or reply fast.",
    climate: "letter paper and warm margin",
    entry: "Open letters",
    runtime: "Letter write/read shell",
    aiHook: "Safety review and gentle language support",
    pricing: "Free daily letter / $3.99 saved letters and stationery",
    coverTone: "paper",
  },
  {
    id: "desert-starscape",
    hall: "playground",
    title: "Desert Starscape",
    originalName: "星空沙漠・动态冥想",
    summary: "A slow desert horizon with moving stars, dusk, moon, and quiet modes.",
    climate: "sand, stars, dusk light",
    entry: "Open stars",
    runtime: "Visual scene shell and mode switch",
    aiHook: "Background sound and sky variation",
    pricing: "Free base mode / $4.99 full modes and background sound",
    coverTone: "desert",
  },
  {
    id: "arabesque-garden",
    hall: "playground",
    title: "Arabesque Garden",
    originalName: "阿拉伯花园・无压力种植",
    summary: "A no-fail courtyard garden with desert roses, jasmine, and quiet ornaments.",
    climate: "courtyard, mosaic, desert plants",
    entry: "Open courtyard",
    runtime: "Garden shell and placement slots",
    aiHook: "Plant change and courtyard variation",
    pricing: "Free base garden / $2.99 rare seeds and courtyard decor",
    coverTone: "desert",
  },
  {
    id: "sand-texture-zen",
    hall: "playground",
    title: "Sand Texture Zen",
    originalName: "沙之纹理・极简ASMR拼图",
    summary: "A slow sand and geometry puzzle with no time limit and wallpaper output.",
    climate: "sand texture and soft geometry",
    entry: "Open texture",
    runtime: "Puzzle shell and wallpaper output placeholder",
    aiHook: "Pattern generation and phrase translation",
    pricing: "Free base puzzle / $3.99 full set and wallpaper pack",
    coverTone: "desert",
  },
  {
    id: "courtyard-water-calm",
    hall: "playground",
    title: "Courtyard Water Calm",
    originalName: "庭院水音・正念滴水",
    summary: "A courtyard water surface with slow drops, ripples, and adjustable pace.",
    climate: "water, tile, slow ripple",
    entry: "Open water",
    runtime: "Drop speed shell and sound placeholder",
    aiHook: "Water sound matching and scene tone",
    pricing: "Free base mode / $2.99 scenes and custom water pace",
    coverTone: "water",
  },
  {
    id: "quiet-arabic-notes",
    hall: "playground",
    title: "Quiet Arabic Notes",
    originalName: "古文字疗愈・匿名温暖便签",
    summary: "Anonymous warm notes on a quiet wall, readable without social pressure.",
    climate: "wall note, warm paper, regional texture",
    entry: "Open notes",
    runtime: "Note wall shell and moderation placeholder",
    aiHook: "Language support, safety review, and background templates",
    pricing: "Free daily note / $2.99 saved notes and background templates",
    coverTone: "desert",
  },
] as const;

export const healingModules: readonly HealingModule[] = healingModuleSeeds.map((module) => {
  const room = browserAirModuleNames[module.id];

  return {
    ...module,
    title: room.title,
    summary: room.roomLine,
    climate: room.weatherLine,
    entry: room.quietEntrance,
    runtime: room.traceLine,
    aiHook: "Atmosphere may adapt softly when real room context is present.",
    pricing: "Kept low-pressure and optional.",
    roomLine: room.roomLine,
    weatherLine: room.weatherLine,
    traceLine: room.traceLine,
    quietEntrance: room.quietEntrance,
  };
});

export function healingHallById(id: string) {
  return healingHalls.find((hall) => hall.id === id);
}

export function healingModulesForHall(hallId: HealingHallId) {
  return healingModules.filter((module) => module.hall === hallId);
}

export function healingModuleById(id: string) {
  return healingModules.find((module) => module.id === id);
}

export const healingCoreEntries = [
  "daily-verse",
  "cloud-meditation-altar",
  "quiet-moments-subscription",
  "emotion-garden",
] as const;

export const windkeepHealingSurfaces = [
  {
    title: "Windkeep",
    summary: "Object passage, care notes, and things that keep moving through real rooms.",
    href: "/objects#driftbox",
  },
  {
    title: "Driftbox",
    summary: "A quiet receiving place for objects, emotions, and notes after use.",
    href: "/objects#driftbox",
  },
  {
    title: "Quiet Passage",
    summary: "Future object circulation without selling-floor pressure or public bidding energy.",
    href: "/inquiry",
  },
  {
    title: "Object Stories",
    summary: "Small histories around old objects before they become products or archive pieces.",
    href: "/healing/stories",
  },
] as const;
